### PR TITLE
Submit initial version of Codewars.hs

### PR DESCRIPTION
**Pull request by Bubbler-4**
Directly copied code from [this kumite](https://www.codewars.com/kumite/5c5cabb78dac194b19d61072?sel=5c5cabb78dac194b19d61072).

Includes two main functionalities:

* `solutionShouldHide`, `solutionShouldHideAll` replaces the legacy `hidden` functionality.
* `shouldBeApprox`, `shouldBeApproxPrec` can be used for floating-point assertions.
  * `shouldBeApprox` has default absolute/relative margin of `1e-6`.

### CODE REVIEW

**Comment by Bubbler-4** [comment]
Now that I think of it, shouldn't the path have been `src/Test/Hspec/Codewars.hs`?

**Comment by kazk** [comment]
Yeah, I think that's better. Can you move it?

**Comment by Bubbler-4** [comment]
Done, though I slightly messed up in the way.

**Comment by kazk** [comment]
Don't worry, I'll squash it when merging.

Thanks for doing this. Looks great :+1: 
I'll let you know when it becomes available on Codewars. Maybe early next week.

**Pull request merged**
